### ISSUE TITLE
Create API serivce

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/lnp-node#3]
We need the node to have an API for their clients. We will use ZMQ for that. Basically, it has to be implemented as a separate `api` service using https://github.com/LNP-BP/lnpd/blob/master/src/service.rs in the same way as was done for API service in `txserv`:

*  Main `runtime` creating and managing REQ/REP and PUB/SUB pair: https://github.com/LNP-BP/txserv/blob/master/txparserd/src/input/runtime/mod.rs
* REQ/REP task: https://github.com/LNP-BP/txserv/blob/master/txparserd/src/input/runtime/responder.rs
* PUB/SUB task: https://github.com/LNP-BP/txserv/blob/master/txparserd/src/input/runtime/publisher.rs

**Comment by St333p** [comment]
As said in the mattermost, I'll try to take this issue, but I'm not sure I'll succeed since I'm new to rust. If it becomes blocking for something else just let me know and let some expert work on it.
