### ISSUE TITLE
asset identifier confusion

### ISSUE THREAD

**Issue by St333p** [LNP-BP/lnp-node#33]
Currently lnp-node uses different encodings to identify rgb assets, mixing big-endian and little-endian `hex` formats. This should be solved, as discussed in 2020/12/09 devcall and reported in #31, by uniforming them to `bech32` encoding, which will be available in one of the next versions of lnpbp core library.

*Note: this issue aims to collect info related to this topic while rust-lnpbp is released.*

**Comment by dr-orlovsky** [comment]
Should be solved with the recent updates
